Repository jahazielBH/app-web, pull requests merged in 2020-12, with the labels that each got.

#25 API - Login to develop
  dist/app-web/3rdpartylicenses.txt
  dist/app-web/imagen.jpg
  dist/app-web/index.html
  dist/app-web/layers-2x.png
  dist/app-web/layers.png
  dist/app-web/main.0e87d09a8470d3829ea8.js
  dist/app-web/main.js
  dist/app-web/main.js.map
  dist/app-web/marker-icon.png
  dist/app-web/polyfills.35a5ca1855eb057f016a.js
  dist/app-web/polyfills.js
  dist/app-web/polyfills.js.map
  dist/app-web/runtime.acf0dec4155e77772545.js
  dist/app-web/runtime.js
  dist/app-web/runtime.js.map
  dist/app-web/styles.02b761c168e3621ee406.css
  dist/app-web/styles.js
  dist/app-web/styles.js.map
  dist/app-web/vendor.js
  dist/app-web/vendor.js.map
  src/app/app.component.html
  src/app/app.component.spec.ts
  src/app/app.module.ts
  src/app/header/header.component.html
  src/app/header/header.component.scss
  src/app/header/header.component.spec.ts
  src/app/header/header.component.ts
  src/app/login/login.component.html
  src/app/login/login.component.scss
  src/app/login/login.component.spec.ts
  src/app/login/login.component.ts
  src/app/map/map.component.html
  src/app/map/map.component.scss
  src/app/map/map.component.ts
  src/app/models/responseapi.ts
  src/app/models/userapire.ts
  src/app/models/usersapi.ts
  src/app/registro/registro.component.html
  src/app/registro/registro.component.scss
  src/app/registro/registro.component.spec.ts
  src/app/registro/registro.component.ts
  src/app/services/storage.service.ts
  src/app/services/users.service.spec.ts
  src/app/services/users.service.ts
Labels: PR, enhancement

#27 login to registro
  src/app/login/login.component.ts
  src/app/registro/registro.component.ts
  src/app/services/storage.service.ts
  src/app/services/users.service.ts
Labels: PR

#28 Registro to develop
  src/app/login/login.component.ts
  src/app/registro/registro.component.ts
  src/app/services/storage.service.ts
  src/app/services/users.service.ts
Labels: PR

#29 Develop to release
  dist/app-web/3rdpartylicenses.txt
  dist/app-web/imagen.jpg
  dist/app-web/index.html
  dist/app-web/layers-2x.png
  dist/app-web/layers.png
  dist/app-web/main.0e87d09a8470d3829ea8.js
  dist/app-web/main.js
  dist/app-web/main.js.map
  dist/app-web/marker-icon.png
  dist/app-web/polyfills.35a5ca1855eb057f016a.js
  dist/app-web/polyfills.js
  dist/app-web/polyfills.js.map
  dist/app-web/runtime.acf0dec4155e77772545.js
  dist/app-web/runtime.js
  dist/app-web/runtime.js.map
  dist/app-web/styles.02b761c168e3621ee406.css
  dist/app-web/styles.js
  dist/app-web/styles.js.map
  dist/app-web/vendor.js
  dist/app-web/vendor.js.map
  src/app/app.component.html
  src/app/app.component.spec.ts
  src/app/app.module.ts
  src/app/header/header.component.html
  src/app/header/header.component.scss
  src/app/header/header.component.spec.ts
  src/app/header/header.component.ts
  src/app/login/login.component.html
  src/app/login/login.component.scss
  src/app/login/login.component.spec.ts
  src/app/login/login.component.ts
  src/app/map/map.component.html
  src/app/map/map.component.scss
  src/app/map/map.component.ts
  src/app/models/responseapi.ts
  src/app/models/userapire.ts
  src/app/models/usersapi.ts
  src/app/registro/registro.component.html
  src/app/registro/registro.component.scss
  src/app/registro/registro.component.spec.ts
  src/app/registro/registro.component.ts
  src/app/services/storage.service.ts
  src/app/services/users.service.spec.ts
  src/app/services/users.service.ts
Labels: PR

#30 Release to master
  dist/app-web/3rdpartylicenses.txt
  dist/app-web/imagen.jpg
  dist/app-web/index.html
  dist/app-web/layers-2x.png
  dist/app-web/layers.png
  dist/app-web/main.0e87d09a8470d3829ea8.js
  dist/app-web/main.js
  dist/app-web/main.js.map
  dist/app-web/marker-icon.png
  dist/app-web/polyfills.35a5ca1855eb057f016a.js
  dist/app-web/polyfills.js
  dist/app-web/polyfills.js.map
  dist/app-web/runtime.acf0dec4155e77772545.js
  dist/app-web/runtime.js
  dist/app-web/runtime.js.map
  dist/app-web/styles.02b761c168e3621ee406.css
  dist/app-web/styles.js
  dist/app-web/styles.js.map
  dist/app-web/vendor.js
  dist/app-web/vendor.js.map
  src/app/app.component.html
  src/app/app.component.spec.ts
  src/app/app.module.ts
  src/app/header/header.component.html
  src/app/header/header.component.scss
  src/app/header/header.component.spec.ts
  src/app/header/header.component.ts
  src/app/login/login.component.html
  src/app/login/login.component.scss
  src/app/login/login.component.spec.ts
  src/app/login/login.component.ts
  src/app/map/map.component.html
  src/app/map/map.component.scss
  src/app/map/map.component.ts
  src/app/models/responseapi.ts
  src/app/models/userapire.ts
  src/app/models/usersapi.ts
  src/app/registro/registro.component.html
  src/app/registro/registro.component.scss
  src/app/registro/registro.component.spec.ts
  src/app/registro/registro.component.ts
  src/app/services/storage.service.ts
  src/app/services/users.service.spec.ts
  src/app/services/users.service.ts
Labels: PR

#33 Closes #23
  dist/app-web/assets/img/imagen.jpg
  dist/app-web/assets/img/usuario.png
  dist/app-web/index.html
  dist/app-web/main.js
  dist/app-web/main.js.map
  dist/app-web/polyfills.js
  dist/app-web/polyfills.js.map
  dist/app-web/styles.js
  dist/app-web/styles.js.map
  dist/app-web/usuario.png
  src/app/admin/admin.component.html
  src/app/admin/admin.component.scss
  src/app/admin/admin.component.spec.ts
  src/app/admin/admin.component.ts
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/auth/auth-interceptor.ts
  src/app/auth/auth.service.ts
  src/app/auth/jwt-response.ts
  src/app/auth/login-info.ts
  src/app/auth/token-storage.service.ts
  src/app/header/header.component.html
  src/app/header/header.component.spec.ts
  src/app/header/header.component.ts
  src/app/home/home.component.html
  src/app/home/home.component.scss
  src/app/home/home.component.spec.ts
  src/app/home/home.component.ts
  src/app/login/login.component.html
  src/app/login/login.component.scss
  src/app/login/login.component.spec.ts
  src/app/login/login.component.ts
  src/app/map/map.component.ts
  src/app/models/responseapi.ts
  src/app/models/userapire.ts
  src/app/models/usersapi.ts
  src/app/pm/pm.component.html
  src/app/pm/pm.component.scss
  src/app/pm/pm.component.spec.ts
  src/app/pm/pm.component.ts
  src/app/registro/registro.component.html
  src/app/registro/registro.component.scss
  src/app/registro/registro.component.ts
  src/app/services/storage.service.ts
  src/app/services/user.service.spec.ts
  src/app/services/user.service.ts
  src/app/services/users.service.spec.ts
  src/app/services/users.service.ts
  src/app/user/user.component.html
  src/app/user/user.component.scss
  src/app/user/user.component.spec.ts
  src/app/user/user.component.ts
  src/assets/img/imagen.jpg
  src/assets/img/usuario.png
  src/index.html
Labels: PR, bug

#34 Closes #24
  dist/app-web/main.js
  dist/app-web/main.js.map
  src/app/auth/auth.service.ts
  src/app/auth/signup-info.ts
  src/app/login/login.component.html
  src/app/registro/registro.component.html
  src/app/registro/registro.component.scss
  src/app/registro/registro.component.spec.ts
  src/app/registro/registro.component.ts
Labels: PR, bug

#35 Develop to release
  dist/app-web/assets/img/imagen.jpg
  dist/app-web/assets/img/usuario.png
  dist/app-web/index.html
  dist/app-web/main.js
  dist/app-web/main.js.map
  dist/app-web/polyfills.js
  dist/app-web/polyfills.js.map
  dist/app-web/styles.js
  dist/app-web/styles.js.map
  dist/app-web/usuario.png
  src/app/admin/admin.component.html
  src/app/admin/admin.component.scss
  src/app/admin/admin.component.spec.ts
  src/app/admin/admin.component.ts
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/auth/auth-interceptor.ts
  src/app/auth/auth.service.ts
  src/app/auth/jwt-response.ts
  src/app/auth/login-info.ts
  src/app/auth/signup-info.ts
  src/app/auth/token-storage.service.ts
  src/app/header/header.component.html
  src/app/header/header.component.spec.ts
  src/app/header/header.component.ts
  src/app/home/home.component.html
  src/app/home/home.component.scss
  src/app/home/home.component.spec.ts
  src/app/home/home.component.ts
  src/app/login/login.component.html
  src/app/login/login.component.scss
  src/app/login/login.component.spec.ts
  src/app/login/login.component.ts
  src/app/map/map.component.ts
  src/app/models/responseapi.ts
  src/app/models/userapire.ts
  src/app/models/usersapi.ts
  src/app/pm/pm.component.html
  src/app/pm/pm.component.scss
  src/app/pm/pm.component.spec.ts
  src/app/pm/pm.component.ts
  src/app/registro/registro.component.html
  src/app/registro/registro.component.scss
  src/app/registro/registro.component.spec.ts
  src/app/registro/registro.component.ts
  src/app/services/storage.service.ts
  src/app/services/user.service.spec.ts
  src/app/services/user.service.ts
  src/app/services/users.service.spec.ts
  src/app/services/users.service.ts
  src/app/user/user.component.html
  src/app/user/user.component.scss
  src/app/user/user.component.spec.ts
  src/app/user/user.component.ts
  src/assets/img/imagen.jpg
  src/assets/img/usuario.png
  src/index.html
Labels: PR
